### ISSUE TITLE
How to change geometry in code ocean

### ISSUE THREAD

**Issue by gesx123** [cselab/aphros#18]
Hello Dr Karnakov, I am using the case you provided under the examples/205_multivof/bidisperse path for my simulation. I tried to change some of the model geometry and fluid property parameters, and some of the problems could not be solved.

1. I want to connect a converging channel followed by a diverging channel in the examples/205_multivof/bidisperse/gen file. I made the following modifications: change `lx = Lwide + Lnarrow + H * 0.5 `  to ` lx = 2 * Lwide +2 * Lnarrow + H * 0.5 *2`.
![image](https://github.com/cselab/aphros/assets/157437651/263d9b8c-1c89-4fc3-b855-72e62b04c525)
After performing a "reproducible run," the generated files still follow the calculations from the original gen file, and the geometric structure has not changed.
2.  I couldn't find the exact meaning of "invert" and "intersect" with a value of 1 in the Geometry class.
3. If I want to simulate the flow of a droplet cluster, can I directly modify the density and viscosity of the dispersed phase in the gen file?

**Comment by gesx123** [comment]
For the first question, when I directly input the contents of the 'gen' file into the 'bidisperse.sh' script, the computation can proceed. But when I attempt a long-duration simulation (tmax > 0.8), the following error occurs:
`ERROR: In /build/paraview-lH8wFv/paraview-5.4.1+dfsg3/VTK/IO/Parallel/vtkPDataSetReader.cxx, line 858
vtkPDataSetReader (0x55d198e5b7a0): Initialize: Could not open file ../bc.vtk

ERROR: In /build/paraview-lH8wFv/paraview-5.4.1+dfsg3/VTK/Common/ExecutionModel/vtkExecutive.cxx, line 784
vtkPVCompositeDataPipeline (0x55d1966f9e00): Algorithm vtkFileSeriesReader(0x55d198d31380) returned failure for request: vtkInformation (0x55d198f73210)
  Debug: Off
  Modified Time: 201562
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FORWARD_DIRECTION: 0
  FROM_OUTPUT_PORT: 0
  ALGORITHM_AFTER_FORWARD: 1`

**Comment by gesx123** [comment]
The issue regarding simulation time has been resolved, and it appears to be related to the format of the parameters.

**Comment by pkarnakov** [comment]
Hi, sorry for the late reply!
1. You could try to run `gen` locally on your computer and look at the generated `body.dat`, then also use the "Flowing crystal" case from the [gallery](https://github.com/cselab/aphros/wiki/Aphros-Explorer). Maybe you also need `make clean` before running `./gen`.
2. `invert` multiples the negates the function and `intersect` applies an intersection operation to the currently accumulated field. They correspond to `-` and `&` in the documentation about [geometric primitives](https://cselab.github.io/aphros/doc/#geometric-primitives)
3. Yes you can directly modify `rho` and `mu` in the file. It may want to adjust the definition of `Re` accordingly so that it follows the denser phase
